#!/usr/bin/env node
const { exec } = require("child_process");
const path = require("path");

const file = path.basename(process.argv[2], ".rs");

exec(`cat ${file}_input | cargo run --bin=${file}`, (err, stdout, stderr) => {
  console.log(stdout);
  console.log(stderr);
});
