#!/usr/bin/env node
const { exec } = require("child_process");
const path = require("path");

if (process.argv.length < 3) {
  console.log("./run {filename without extension}");
  process.exit();
}

const file = path.basename(process.argv[2]);

exec(`cd graph_theory; cat ${file}_input | cargo run --bin=${file}`, (err, stdout, stderr) => {
  console.log(stdout);
  console.log(stderr);
});
